language: ruby
bundler_args: --without production --quiet
before_install:
  - gem update --system
  - gem --version
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install: ruby -S bundle install
script:
  - bundle exec rake test
rvm:
  - 2.3.4
sudo: false
