# Encoding
encoding: utf-8

# Site
title: JoshAdamBoyd
email: joshadamboyd@mac.com
description: This is the personal website of Josh Adam Boyd. I'm a UX Designer for projekt202 living in McKinney Texas.
keywords:
  - UX Designer
  - Illustrator
  - Blog
  - Josh Adam Boyd
  - Josh Boyd
  - JoshAdamBoyd
  - Portfolio
  - Graphic Designer
  - McKinney TX

# URLs
baseurl: ""
url: https://joshadamboyd.github.io

# Comments
comments:
  disqus:

# Analytics
analytics:
  google: UA-5762082-1

# Social media
social:
  dribbble: joshadamboyd
  facebook:
  github:
  instagram: joshadamboyd
  linkedin:
  twitter: joshadamboyd
  youtube: joshadamboyd

# Markdown
markdown: kramdown

# Pagination
paginate: 12
permalink: articles/:title/
paginate_path: articles/page/:num/

# Timezone
timezone: America/Chicago

# Collections
collections:
  portfolio:
    output: false

# Defaults
defaults:
  # Portfolio
  -
    scope:
      type: portfolio
    values:
      type: portfolio
      layout: page
  # Posts
  -
    scope:
      type: posts
    values:
      type: post
      layout: post
      comments: true
  # Pages
  -
    scope:
      type: pages
    values:
      type: page
      layout: page

# CSS compression
sass:
  style: :compressed
  # style: :expanded

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude in build
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - yarn.lock
