# Site
title: JoshAdamBoyd # Name of your site
email: joshadamboyd@mac.com # Your email address
description: This is the personal website of Josh Adam Boyd. I'm a UX Designer for projekt202 living in McKinney Texas. # Default description of your site
keywords: # Site keywords
  - UX
  - Designer
  - Illustrator
  - Blog
  - Josh Adam Boyd
  - Josh Boyd
  - JoshAdamBoyd


# URLs and paths
baseurl: "" # Base path of your site. Useful when your Jekyll site is at /blog
url: http://joshadamboyd.github.io # Base URL of your site

# Social networks
social: # Social media usernames
  dribbble: joshadamboyd
  facebook:
  github:
  instagram: joshadamboyd
  linkedin:
  twitter: joshadamboyd

# Comments
comments:
  provider: disqus # Comments provider. Only one can be used
  disqus:
    short_name: joshadamboyd
  facebook:
    app_id:
    num_posts: 5
    width: 100%
    colorscheme: light

# Analytics
analytics: # Site analytics. Multiple can be used at the same time
  google:
    tracking_id: UA-5762082-1
  mixpanel:
    token:

# Site verification
verification:
  google:
  msvalidate:

# Pagination
paginate: 12 # Number of posts to display per page
permalink: /:year/:month/:title/ # Post URL format
paginate_path: /page/:num # Post pagination URL format

# Timezone
timezone: America/Chicago # Your timezone

# Collections
collections:
  timeline:
    output: false
  portfolio:
    output: true

# Share
share:
  email: false
  facebook: true
  linkedin: true
  twitter: true
  google: true
  pinterest: false

# Default layouts
defaults:
  - scope:
      type: portfolio
    values:
      type: portfolio
      layout: portfolio
      share: false
  - scope:
      type: posts
    values:
      type: post
      layout: post
      comments: true
      highlight:
      share: false
  - scope:
      type: pages
    values:
      type: page
      layout: page
      share: false

# CSS compression
sass:
  # style: expanded
  style: :compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag

# Exclude in build
exclude:
  - README.md

# Highlighter
highlighter: rouge
